# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cast_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cast_control.proto',
  package='cast_control',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63\x61st_control.proto\x12\x0c\x63\x61st_control\"\x18\n\x08\x44\x65viceID\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\x87\x01\n\x06\x44\x65vice\x12\x15\n\rfriendly_name\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x03 \x01(\t\x12)\n\tdevice_id\x18\x04 \x01(\x0b\x32\x16.cast_control.DeviceID\x12\x11\n\tcast_type\x18\x05 \x01(\t\"\'\n\x06Status\x12\x0e\n\x06volume\x18\x01 \x01(\x01\x12\r\n\x05muted\x18\x02 \x01(\x08\"\x18\n\x06Volume\x12\x0e\n\x06volume\x18\x01 \x01(\x01\"\x13\n\x11ListDeviceRequest\"Y\n\x13\x41\x64justVolumeRequest\x12)\n\tdevice_id\x18\x01 \x01(\x0b\x32\x16.cast_control.DeviceID\x12\x17\n\x0frelative_volume\x18\x02 \x01(\x01\"M\n\x10SetVolumeRequest\x12)\n\tdevice_id\x18\x01 \x01(\x0b\x32\x16.cast_control.DeviceID\x12\x0e\n\x06volume\x18\x02 \x01(\x01\x32\xaa\x02\n\x0b\x43\x61stControl\x12H\n\x0bListDevices\x12\x1f.cast_control.ListDeviceRequest\x1a\x14.cast_control.Device\"\x00\x30\x01\x12\x41\n\x0fGetDeviceStatus\x12\x16.cast_control.DeviceID\x1a\x14.cast_control.Status\"\x00\x12I\n\x0c\x41\x64justVolume\x12!.cast_control.AdjustVolumeRequest\x1a\x14.cast_control.Volume\"\x00\x12\x43\n\tSetVolume\x12\x1e.cast_control.SetVolumeRequest\x1a\x14.cast_control.Volume\"\x00\x62\x06proto3')
)




_DEVICEID = _descriptor.Descriptor(
  name='DeviceID',
  full_name='cast_control.DeviceID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='cast_control.DeviceID.uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=60,
)


_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='cast_control.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friendly_name', full_name='cast_control.Device.friendly_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='cast_control.Device.model_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manufacturer', full_name='cast_control.Device.manufacturer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='cast_control.Device.device_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cast_type', full_name='cast_control.Device.cast_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=198,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='cast_control.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='cast_control.Status.volume', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='muted', full_name='cast_control.Status.muted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=239,
)


_VOLUME = _descriptor.Descriptor(
  name='Volume',
  full_name='cast_control.Volume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='cast_control.Volume.volume', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=265,
)


_LISTDEVICEREQUEST = _descriptor.Descriptor(
  name='ListDeviceRequest',
  full_name='cast_control.ListDeviceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=286,
)


_ADJUSTVOLUMEREQUEST = _descriptor.Descriptor(
  name='AdjustVolumeRequest',
  full_name='cast_control.AdjustVolumeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='cast_control.AdjustVolumeRequest.device_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='relative_volume', full_name='cast_control.AdjustVolumeRequest.relative_volume', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=377,
)


_SETVOLUMEREQUEST = _descriptor.Descriptor(
  name='SetVolumeRequest',
  full_name='cast_control.SetVolumeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='cast_control.SetVolumeRequest.device_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='cast_control.SetVolumeRequest.volume', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=456,
)

_DEVICE.fields_by_name['device_id'].message_type = _DEVICEID
_ADJUSTVOLUMEREQUEST.fields_by_name['device_id'].message_type = _DEVICEID
_SETVOLUMEREQUEST.fields_by_name['device_id'].message_type = _DEVICEID
DESCRIPTOR.message_types_by_name['DeviceID'] = _DEVICEID
DESCRIPTOR.message_types_by_name['Device'] = _DEVICE
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Volume'] = _VOLUME
DESCRIPTOR.message_types_by_name['ListDeviceRequest'] = _LISTDEVICEREQUEST
DESCRIPTOR.message_types_by_name['AdjustVolumeRequest'] = _ADJUSTVOLUMEREQUEST
DESCRIPTOR.message_types_by_name['SetVolumeRequest'] = _SETVOLUMEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceID = _reflection.GeneratedProtocolMessageType('DeviceID', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEID,
  __module__ = 'cast_control_pb2'
  # @@protoc_insertion_point(class_scope:cast_control.DeviceID)
  ))
_sym_db.RegisterMessage(DeviceID)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), dict(
  DESCRIPTOR = _DEVICE,
  __module__ = 'cast_control_pb2'
  # @@protoc_insertion_point(class_scope:cast_control.Device)
  ))
_sym_db.RegisterMessage(Device)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'cast_control_pb2'
  # @@protoc_insertion_point(class_scope:cast_control.Status)
  ))
_sym_db.RegisterMessage(Status)

Volume = _reflection.GeneratedProtocolMessageType('Volume', (_message.Message,), dict(
  DESCRIPTOR = _VOLUME,
  __module__ = 'cast_control_pb2'
  # @@protoc_insertion_point(class_scope:cast_control.Volume)
  ))
_sym_db.RegisterMessage(Volume)

ListDeviceRequest = _reflection.GeneratedProtocolMessageType('ListDeviceRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTDEVICEREQUEST,
  __module__ = 'cast_control_pb2'
  # @@protoc_insertion_point(class_scope:cast_control.ListDeviceRequest)
  ))
_sym_db.RegisterMessage(ListDeviceRequest)

AdjustVolumeRequest = _reflection.GeneratedProtocolMessageType('AdjustVolumeRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADJUSTVOLUMEREQUEST,
  __module__ = 'cast_control_pb2'
  # @@protoc_insertion_point(class_scope:cast_control.AdjustVolumeRequest)
  ))
_sym_db.RegisterMessage(AdjustVolumeRequest)

SetVolumeRequest = _reflection.GeneratedProtocolMessageType('SetVolumeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETVOLUMEREQUEST,
  __module__ = 'cast_control_pb2'
  # @@protoc_insertion_point(class_scope:cast_control.SetVolumeRequest)
  ))
_sym_db.RegisterMessage(SetVolumeRequest)



_CASTCONTROL = _descriptor.ServiceDescriptor(
  name='CastControl',
  full_name='cast_control.CastControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=459,
  serialized_end=757,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListDevices',
    full_name='cast_control.CastControl.ListDevices',
    index=0,
    containing_service=None,
    input_type=_LISTDEVICEREQUEST,
    output_type=_DEVICE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDeviceStatus',
    full_name='cast_control.CastControl.GetDeviceStatus',
    index=1,
    containing_service=None,
    input_type=_DEVICEID,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AdjustVolume',
    full_name='cast_control.CastControl.AdjustVolume',
    index=2,
    containing_service=None,
    input_type=_ADJUSTVOLUMEREQUEST,
    output_type=_VOLUME,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetVolume',
    full_name='cast_control.CastControl.SetVolume',
    index=3,
    containing_service=None,
    input_type=_SETVOLUMEREQUEST,
    output_type=_VOLUME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CASTCONTROL)

DESCRIPTOR.services_by_name['CastControl'] = _CASTCONTROL

# @@protoc_insertion_point(module_scope)
