# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cast_control_pb2 as cast__control__pb2


class CastControlStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListDevices = channel.unary_stream(
        '/cast_control.CastControl/ListDevices',
        request_serializer=cast__control__pb2.ListDeviceRequest.SerializeToString,
        response_deserializer=cast__control__pb2.Device.FromString,
        )
    self.GetDeviceStatus = channel.unary_unary(
        '/cast_control.CastControl/GetDeviceStatus',
        request_serializer=cast__control__pb2.DeviceID.SerializeToString,
        response_deserializer=cast__control__pb2.Status.FromString,
        )
    self.AdjustVolume = channel.unary_unary(
        '/cast_control.CastControl/AdjustVolume',
        request_serializer=cast__control__pb2.AdjustVolumeRequest.SerializeToString,
        response_deserializer=cast__control__pb2.Volume.FromString,
        )
    self.SetVolume = channel.unary_unary(
        '/cast_control.CastControl/SetVolume',
        request_serializer=cast__control__pb2.SetVolumeRequest.SerializeToString,
        response_deserializer=cast__control__pb2.Volume.FromString,
        )


class CastControlServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListDevices(self, request, context):
    """Method definitions go here
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetDeviceStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AdjustVolume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetVolume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CastControlServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListDevices': grpc.unary_stream_rpc_method_handler(
          servicer.ListDevices,
          request_deserializer=cast__control__pb2.ListDeviceRequest.FromString,
          response_serializer=cast__control__pb2.Device.SerializeToString,
      ),
      'GetDeviceStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetDeviceStatus,
          request_deserializer=cast__control__pb2.DeviceID.FromString,
          response_serializer=cast__control__pb2.Status.SerializeToString,
      ),
      'AdjustVolume': grpc.unary_unary_rpc_method_handler(
          servicer.AdjustVolume,
          request_deserializer=cast__control__pb2.AdjustVolumeRequest.FromString,
          response_serializer=cast__control__pb2.Volume.SerializeToString,
      ),
      'SetVolume': grpc.unary_unary_rpc_method_handler(
          servicer.SetVolume,
          request_deserializer=cast__control__pb2.SetVolumeRequest.FromString,
          response_serializer=cast__control__pb2.Volume.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cast_control.CastControl', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
